version: '3'
services:
  cost-manager:
    image: cost-manager:latest
    ports:
      - "49160:3000"
    environment:
      - KAFKA_URL=kafka1:9092,kafka2:9092,kafka3:9092
networks:
  default:
    external:
      name: kafka-docker-compose_kafka
